language: cpp
compiler: gcc
sudo: require
dist: xenial

env:
  - CC=gcc-7 CXX=g++-7 CXX_COMPILER=g++-7 C_COMPILER=gcc-7
  
before_install:
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y # Does this install newer libstdc++? Then prepare for trouble
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt512base libgl1-mesa-dev g++-7
  - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake CONFIG+=release PREFIX=/usr # "QMAKE_CXXFLAGS += -std=c++1z"
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh File_Commander*.AppImage*
  
branches:
  except:
    # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
